# Generated by Django 6.0.1 on 2026-02-03 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numbercar',
            old_name='nameCar',
            new_name='name_car',
        ),
        migrations.RenameField(
            model_name='numbercar',
            old_name='nummer_Car',
            new_name='number_car',
        ),
        migrations.AlterField(
            model_name='documentcar',
            name='choice_car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='relation_db.numbercar'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=1)),
                ('text', models.CharField(default='good car', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='relation_db.numbercar')),
            ],
        ),
    ]
