# Generated by Django 6.0.1 on 2026-02-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proglang',
            name='views',
            field=models.PositiveBigIntegerField(default=0, verbose_name='количество просмотров'),
        ),
    ]
